name: ksu_budidaya
description: Aplikasi KSU Budidaya.
publish_to: "none"
version: 1.0.0
environment:
  sdk: ">=3.0.0 <=3.3.4"
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  flutter_svg: ^2.0.10+1
  hive: ^2.2.3
  path_provider: ^2.1.3
  change_app_package_name: ^1.1.0
  lottie: ^2.3.0
  flutter_animate: ^4.1.0
  dio: ^5.0.3
  validatorless: ^1.2.3
  google_fonts: ^4.0.4
  flutter_countdown_timer: ^4.1.0
  json_annotation: ^4.8.1
  dart_pusher_channels: ^1.1.1
  qr_flutter: ^4.1.0
  flutter_localization: ^0.1.13
  dropdown_search: ^5.0.6
  package_info_plus: ^4.0.2
  url_launcher: ^6.2.6
  provider: ^6.1.2
  flutter_switch: ^0.3.2
  camera: ^0.11.0+1
  image: ^4.1.3
  dolumns: ^2.0.1
  flutter_usb_printer: ^0.1.0+1
  flutter_image_preview: ^0.1.1
  pdf: ^3.10.8
  printing: ^5.11.1
  geolocator: ^10.1.0
  dropdown_button2: ^2.3.9
  skeletonizer: ^1.0.1
  easy_image_viewer: ^1.4.0
  go_router: ^13.1.0
  responsive_builder: ^0.7.0
  mobile_scanner: ^5.1.1
  flutter_carousel_widget: ^2.2.0
  connectivity_plus: ^5.0.2
  htmltopdfwidgets: ^1.0.3
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  universal_html: ^2.2.4
  searchfield: ^1.0.5
  permission_handler: ^11.3.1
  mime: ^1.0.5
  pluto_grid_plus: ^8.4.0
  logger: ^2.4.0
  flutter_slider_drawer: ^2.1.3
  easy_stepper: ^0.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.1.1
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  analyzer: ^6.4.1
flutter:
  uses-material-design: true
  assets:
    - assets/files/json/
    - assets/icons/chevron/
    - assets/icons/info/
    - assets/icons/input/
    - assets/icons/layanan/
    - assets/icons/metode_pembayaran/
    - assets/icons/misc/
    - assets/icons/status/
    - assets/icons/sub_menu/
    - assets/images/illustration/
    - assets/images/logo/
